wwwwwwwwwwwwwwwwwwww  commit

diff --git a/.github/workflows/devsecops.yml b/.github/workflows/devsecops.yml
--- a/.github/workflows/devsecops.yml
+++ b/.github/workflows/devsecops.yml
@@ -28,14 +28,24 @@ jobs:
           pip freeze         # Affiche les dépendances installées
       
 
-    - name:  Install geckodriver
-      if: always()  # Cela garantit que cette étape sera toujours exécutée
+    - name: 🦊 Install geckodriver
       run: |
-          GECKODRIVER_VERSION=$(curl -sSL https://github.com/mozilla/geckodriver/releases/latest | sed 's/.*tag\/v\([^"]*\).*/\1/')
-          curl -sSL https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz -o geckodriver.tar.gz
-          tar -xvzf geckodriver.tar.gz
-          sudo mv geckodriver /usr/local/bin/
-          rm geckodriver.tar.gz
+            # Récupérer la dernière version de geckodriver
+            GECKODRIVER_VERSION=$(curl -sSL https://github.com/mozilla/geckodriver/releases/latest | grep -oP 'v\K[0-9.]+')
+            echo "Installing geckodriver version $GECKODRIVER_VERSION"
+            
+            # Télécharger geckodriver
+            curl -sSL https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz -o geckodriver.tar.gz || { echo "Failed to download geckodriver"; exit 1; }
+            
+            # Extraire le fichier tar
+            tar -xvzf geckodriver.tar.gz || { echo "Failed to extract geckodriver"; exit 1; }
+            
+            # Déplacer geckodriver vers /usr/local/bin/
+            sudo mv geckodriver /usr/local/bin/ || { echo "Failed to move geckodriver"; exit 1; }
+            
+            # Nettoyer le fichier tar
+            rm geckodriver.tar.gz || { echo "Failed to remove geckodriver.tar.gz"; exit 1; }
+        
       
 
     - name:  Run unit tests
